import { localizeUk, localizeEn } from '../../locale';

export const getAboutUk = () => ({
  page_title: localizeUk('Про центр · seed v2'),
  page_subtitle: localizeUk('Single type about-page + колекції Document і Partner'),
  mission_heading: localizeUk('Місія (seed)'),
  mission_h2: localizeUk('Демонструємо, що «Про нас» повністю з CMS'),
  history: localizeUk('Легенда seed v2: центр запущено як тестовий майданчик для дипломного проєкту з Strapi.'),
  structure_description: localizeUk('Структура в адмінці: місія, таймлайн, керівництво, превʼю документів і партнерів.'),
  image_overlay_org: localizeUk('Демо-кампус «Садова»'),
  image_overlay_address: localizeUk('вул. Садова 14 · Дніпро'),
  history_section_title: localizeUk('Хронологія (seed)'),
  history_section_subtitle: localizeUk('Компонент timeline_items'),
  leadership_section_title: localizeUk('Керівництво (seed)'),
  leadership_section_subtitle: localizeUk('Компонент leadership_items'),
  documents_preview_title: localizeUk('Документи — превʼю'),
  documents_preview_subtitle: localizeUk('Перші 6 записів колекції Document'),
  partners_preview_title: localizeUk('Партнери — превʼю'),
  partners_preview_subtitle: localizeUk('Перші 6 записів колекції Partner'),
  mission_checklist: [
    { text: localizeUk('Перевірка single type about-page') },
    { text: localizeUk('Перевірка компонентів repeatable') },
    { text: localizeUk('Превʼю з колекцій') },
    { text: localizeUk('Мітка (new) у всіх рядках') },
  ],
  mission_stats: [
    { value: localizeUk('12'), label: localizeUk('Років seed'), order: 1 },
    { value: localizeUk('880'), label: localizeUk('Демо-слухачів'), order: 2 },
    { value: localizeUk('42'), label: localizeUk('Програм у каталозі'), order: 3 },
  ],
  timeline_items: [
    { year: '2014', title: localizeUk('Старт seed-легенди'), description: localizeUk('Перший запис у timeline_items.'), order: 1 },
    { year: '2018', title: localizeUk('Онлайн-формат'), description: localizeUk('Другий етап — дистанційні курси.'), order: 2 },
    { year: '2022', title: localizeUk('Партнерський хаб'), description: localizeUk('Колекція Partner підключена до About.'), order: 3 },
    { year: '2026', title: localizeUk('Повний CMS'), description: localizeUk('Усі публічні сторінки на Strapi.'), order: 4 },
  ],
  leadership_items: [
    { name: localizeUk('Олена Seedenko'), role: localizeUk('Директор демо'), degree: localizeUk('к.т.н.'), photo_url: 'https://i.pravatar.cc/200?img=32', order: 1 },
    { name: localizeUk('Максим Demochuk'), role: localizeUk('Заступник'), degree: localizeUk('к.е.н.'), photo_url: 'https://i.pravatar.cc/200?img=11', order: 2 },
    { name: localizeUk('Ірина Strapina'), role: localizeUk('Навчальний відділ'), degree: localizeUk('к.пед.н.'), photo_url: 'https://i.pravatar.cc/200?img=25', order: 3 },
    { name: localizeUk('Павло Contentov'), role: localizeUk('Цифрові продукти'), degree: localizeUk('PhD demo'), photo_url: 'https://i.pravatar.cc/200?img=52', order: 4 },
  ],
});

export const getAboutEn = () => ({
  page_title: localizeEn('About the center · seed v2'),
  page_subtitle: localizeEn('about-page single type + Document and Partner collections'),
  mission_heading: localizeEn('Mission (seed)'),
  mission_h2: localizeEn('We show that About is fully CMS-driven'),
  history: localizeEn('Seed v2 lore: the center started as a thesis sandbox for Strapi.'),
  structure_description: localizeEn('Admin structure: mission, timeline, leadership, document and partner previews.'),
  image_overlay_org: localizeEn('Demo campus Sadova'),
  image_overlay_address: localizeEn('14 Sadova St · Dnipro'),
  history_section_title: localizeEn('Timeline (seed)'),
  history_section_subtitle: localizeEn('timeline_items component'),
  leadership_section_title: localizeEn('Leadership (seed)'),
  leadership_section_subtitle: localizeEn('leadership_items component'),
  documents_preview_title: localizeEn('Documents — preview'),
  documents_preview_subtitle: localizeEn('First 6 Document collection entries'),
  partners_preview_title: localizeEn('Partners — preview'),
  partners_preview_subtitle: localizeEn('First 6 Partner collection entries'),
  mission_checklist: [
    { text: localizeEn('Check about-page single type') },
    { text: localizeEn('Check repeatable components') },
    { text: localizeEn('Previews from collections') },
    { text: localizeEn('(new) marker on all rows') },
  ],
  mission_stats: [
    { value: localizeEn('12'), label: localizeEn('Seed years'), order: 1 },
    { value: localizeEn('880'), label: localizeEn('Demo learners'), order: 2 },
    { value: localizeEn('42'), label: localizeEn('Catalog programs'), order: 3 },
  ],
  timeline_items: [
    { year: '2014', title: localizeEn('Seed lore start'), description: localizeEn('First timeline_items row.'), order: 1 },
    { year: '2018', title: localizeEn('Online format'), description: localizeEn('Second stage — distance courses.'), order: 2 },
    { year: '2022', title: localizeEn('Partner hub'), description: localizeEn('Partner collection wired to About.'), order: 3 },
    { year: '2026', title: localizeEn('Full CMS'), description: localizeEn('All public pages on Strapi.'), order: 4 },
  ],
  leadership_items: [
    { name: localizeEn('Olena Seedenko'), role: localizeEn('Demo director'), degree: localizeEn('PhD tech'), photo_url: 'https://i.pravatar.cc/200?img=32', order: 1 },
    { name: localizeEn('Maksym Demochuk'), role: localizeEn('Deputy'), degree: localizeEn('PhD econ'), photo_url: 'https://i.pravatar.cc/200?img=11', order: 2 },
    { name: localizeEn('Iryna Strapina'), role: localizeEn('Academic unit'), degree: localizeEn('PhD ped'), photo_url: 'https://i.pravatar.cc/200?img=25', order: 3 },
    { name: localizeEn('Pavlo Contentov'), role: localizeEn('Digital products'), degree: localizeEn('PhD demo'), photo_url: 'https://i.pravatar.cc/200?img=52', order: 4 },
  ],
});
