import { localizeUk, localizeEn } from '../../locale';

const MAP_URL =
  'https://maps.google.com/maps?width=100%25&height=600&hl=uk&q=48.434606,35.034614+(ДНУ)&t=&z=16&ie=UTF8&iwloc=&output=embed';

export const getContactUk = () => ({
  address: localizeUk('вул. Садова 14, офіс 3Б, м. Дніпро'),
  phone: '+38 (050) 777-00-11',
  email: 'seed-v2@cno.demo',
  working_hours: localizeUk('Пн–Чт: 10:00–18:00, Пт: 10:00–15:00'),
  map_embed_url: MAP_URL,
  facebook_url: 'https://facebook.com/demo-cno-seed',
  instagram_url: 'https://instagram.com/demo_cno_seed',
  contacts_page_title: localizeUk('Звʼязок з командою seed v2'),
  contacts_page_subtitle: localizeUk('Демо-контакти для перевірки Strapi. Усі текстові поля мають мітку (new).'),
  contacts_section_title: localizeUk('Як нас знайти (seed)'),
  apply_sidebar_title: localizeUk('Підтримка абітурієнта (seed)'),
  secondary_phone: '+38 (067) 777-00-22',
  room_note: localizeUk('Кабінет 3Б, 2 поверх, корпус Б'),
  weekend_hours_note: localizeUk('Субота: консультації за записом'),
  footer_about_title: localizeUk('Демо-футер: про центр'),
  footer_about_description: localizeUk('Цей блок редагується в Contact Info у Strapi. Якщо бачите (new) — дані з seed.'),
  footer_nav_title: localizeUk('Демо-навігація'),
  footer_nav_about_label: localizeUk('Про нас (seed)'),
  footer_nav_qualification_label: localizeUk('Короткі курси (seed)'),
  footer_nav_retraining_label: localizeUk('Перекваліфікація (seed)'),
  footer_nav_pre_university_label: localizeUk('Перед ВНЗ (seed)'),
  footer_nav_alumni_label: localizeUk('Випускники (seed)'),
  footer_contacts_title: localizeUk('Контакти (seed)'),
  footer_social_title: localizeUk('Соцмережі (seed)'),
});

export const getContactEn = () => ({
  address: localizeEn('14 Sadova St, office 3B, Dnipro'),
  phone: '+38 (050) 777-00-11',
  email: 'seed-v2@cno.demo',
  working_hours: localizeEn('Mon–Thu: 10:00–18:00, Fri: 10:00–15:00'),
  map_embed_url: MAP_URL,
  facebook_url: 'https://facebook.com/demo-cno-seed',
  instagram_url: 'https://instagram.com/demo_cno_seed',
  contacts_page_title: localizeEn('Contact the seed v2 team'),
  contacts_page_subtitle: localizeEn('Demo contacts to verify Strapi. All text fields include the (new) marker.'),
  contacts_section_title: localizeEn('How to find us (seed)'),
  apply_sidebar_title: localizeEn('Applicant support (seed)'),
  secondary_phone: '+38 (067) 777-00-22',
  room_note: localizeEn('Room 3B, 2nd floor, Building B'),
  weekend_hours_note: localizeEn('Saturday: consultations by appointment'),
  footer_about_title: localizeEn('Demo footer: about'),
  footer_about_description: localizeEn('This block is edited in Contact Info in Strapi. If you see (new), data is from seed.'),
  footer_nav_title: localizeEn('Demo navigation'),
  footer_nav_about_label: localizeEn('About (seed)'),
  footer_nav_qualification_label: localizeEn('Short courses (seed)'),
  footer_nav_retraining_label: localizeEn('Retraining (seed)'),
  footer_nav_pre_university_label: localizeEn('Pre-university (seed)'),
  footer_nav_alumni_label: localizeEn('Alumni (seed)'),
  footer_contacts_title: localizeEn('Contacts (seed)'),
  footer_social_title: localizeEn('Social (seed)'),
});
