import { localizeUk, localizeEn } from '../../locale';

export const getHomeUk = () => ({
  hero_badge_text: localizeUk('Демо-головна · seed v2'),
  hero_title: localizeUk('Навчання, яке видно в Strapi'),
  hero_subtitle: localizeUk('Усі блоки нижче заповнюються з single type home-page. Шукайте суфікс (new) у адмінці.'),
  mission: localizeUk('Місія seed v2: показати повний шлях контенту від CMS до сайту.'),
  stats_graduates: 880,
  stats_programs: 42,
  stats_years: 12,
  stats: [
    { value: '880+', label: localizeUk('Демо-слухачів'), order: 1 },
    { value: '42', label: localizeUk('Демо-програм'), order: 2 },
    { value: '12', label: localizeUk('Років у seed-легенді'), order: 3 },
  ],
  licensed_badge_value: localizeUk('CMS'),
  licensed_badge_label: localizeUk('Контент з Strapi'),
  search_heading: localizeUk('Пошук програм (seed):'),
  search_placeholder: localizeUk('Введіть UX, Data, Agile...'),
  popular_tags_title: localizeUk('Теги з home-page:'),
  popular_tags: [
    { text: localizeUk('UX'), query: localizeUk('UX'), order: 1 },
    { text: localizeUk('Data'), query: localizeUk('Data'), order: 2 },
    { text: localizeUk('Agile'), query: localizeUk('Agile'), order: 3 },
    { text: localizeUk('НМТ'), query: localizeUk('НМТ'), order: 4 },
  ],
  featured_section_title: localizeUk('Обрані програми (seed)'),
  featured_section_subtitle: localizeUk('Список програм — з колекції Program, не з коду'),
  admissions_badge_text: localizeUk('Seed-актуально'),
  admissions_section_title: localizeUk('Дедлайни з CMS'),
  news_section_title: localizeUk('Новини з колекції News'),
  quality_section_title: localizeUk('Блок якості (home-page)'),
  quality_section_description: localizeUk('Цей абзац редагується в Strapi. Якщо зміните тут — сайт оновиться без деплою фронтенду.'),
  bottom_cta_title: localizeUk('Готові тестувати CMS?'),
  bottom_cta_description: localizeUk('Натисніть «Подати заявку» — форма лишається у коді, тексти сторінки — у Strapi.'),
  quality_bullets: [
    { text: localizeUk('Single type: home-page') },
    { text: localizeUk('Колекція: program') },
    { text: localizeUk('Колекція: news (превʼю)') },
    { text: localizeUk('Мітка (new) після re-seed') },
  ],
  direction_cards: [
    { title: localizeUk('Короткі курси'), description: localizeUk('Демо-напрям qualification'), link_path: '/qualification', icon_key: 'trending_up', order: 1 },
    { title: localizeUk('Нова спеціальність'), description: localizeUk('Демо-напрям retraining'), link_path: '/retraining', icon_key: 'briefcase', order: 2 },
    { title: localizeUk('Перед ВНЗ'), description: localizeUk('Демо-напрям pre-university'), link_path: '/pre-university', icon_key: 'award', order: 3 },
  ],
  admissions_cards: [
    { title: localizeUk('Весняний набір (seed)'), description: localizeUk('Текст з компонента admissions_cards'), date_label: localizeUk('Старт: 15.04.2026'), order: 1 },
    { title: localizeUk('Літній інтенсив (seed)'), description: localizeUk('Ще один рядок компонента'), date_label: localizeUk('Старт: 01.07.2026'), order: 2 },
    { title: localizeUk('Осінній цикл (seed)'), description: localizeUk('Третій картка-демо'), date_label: localizeUk('Старт: 01.10.2026'), order: 3 },
  ],
});

export const getHomeEn = () => ({
  hero_badge_text: localizeEn('Demo home · seed v2'),
  hero_title: localizeEn('Learning you can see in Strapi'),
  hero_subtitle: localizeEn('All sections below come from home-page single type. Look for the (new) suffix in admin.'),
  mission: localizeEn('Seed v2 mission: show the full CMS-to-site content path.'),
  stats_graduates: 880,
  stats_programs: 42,
  stats_years: 12,
  stats: [
    { value: '880+', label: localizeEn('Demo learners'), order: 1 },
    { value: '42', label: localizeEn('Demo programs'), order: 2 },
    { value: '12', label: localizeEn('Years in seed lore'), order: 3 },
  ],
  licensed_badge_value: localizeEn('CMS'),
  licensed_badge_label: localizeEn('Content from Strapi'),
  search_heading: localizeEn('Search programs (seed):'),
  search_placeholder: localizeEn('Type UX, Data, Agile...'),
  popular_tags_title: localizeEn('Tags from home-page:'),
  popular_tags: [
    { text: localizeEn('UX'), query: localizeEn('UX'), order: 1 },
    { text: localizeEn('Data'), query: localizeEn('Data'), order: 2 },
    { text: localizeEn('Agile'), query: localizeEn('Agile'), order: 3 },
    { text: localizeEn('NMT'), query: localizeEn('NMT'), order: 4 },
  ],
  featured_section_title: localizeEn('Featured programs (seed)'),
  featured_section_subtitle: localizeEn('Program list comes from Program collection, not code'),
  admissions_badge_text: localizeEn('Seed-relevant'),
  admissions_section_title: localizeEn('Deadlines from CMS'),
  news_section_title: localizeEn('News from News collection'),
  quality_section_title: localizeEn('Quality block (home-page)'),
  quality_section_description: localizeEn('This paragraph is edited in Strapi. Change it here and the site updates without frontend deploy.'),
  bottom_cta_title: localizeEn('Ready to test CMS?'),
  bottom_cta_description: localizeEn('Click Apply — form stays in code, page copy is in Strapi.'),
  quality_bullets: [
    { text: localizeEn('Single type: home-page') },
    { text: localizeEn('Collection: program') },
    { text: localizeEn('Collection: news (preview)') },
    { text: localizeEn('(new) marker after re-seed') },
  ],
  direction_cards: [
    { title: localizeEn('Short courses'), description: localizeEn('Demo track qualification'), link_path: '/qualification', icon_key: 'trending_up', order: 1 },
    { title: localizeEn('New specialty'), description: localizeEn('Demo track retraining'), link_path: '/retraining', icon_key: 'briefcase', order: 2 },
    { title: localizeEn('Pre-university'), description: localizeEn('Demo track pre-university'), link_path: '/pre-university', icon_key: 'award', order: 3 },
  ],
  admissions_cards: [
    { title: localizeEn('Spring intake (seed)'), description: localizeEn('Text from admissions_cards component'), date_label: localizeEn('Start: Apr 15, 2026'), order: 1 },
    { title: localizeEn('Summer intensive (seed)'), description: localizeEn('Another component row'), date_label: localizeEn('Start: Jul 1, 2026'), order: 2 },
    { title: localizeEn('Autumn cycle (seed)'), description: localizeEn('Third demo card'), date_label: localizeEn('Start: Oct 1, 2026'), order: 3 },
  ],
});
