import { localizeUk, localizeEn } from '../../locale';

export const getPreUniversityPageUk = () => ({
  hero_title: localizeUk('НМТ-блок seed v2'),
  hero_subtitle: localizeUk('pre-university-page + колекція pre-university-group для карток предметів.'),
  hero_badge: localizeUk('Демо-набір · перевірка CMS'),
  nmt_exam_date: '2026-06-12',
  countdown_label: localizeUk('до демо-дати НМТ'),
  bundle_title: localizeUk('Пакет: Математика + Історія'),
  bundle_description: localizeUk('Текст bundle з single type — не з коду фронтенду.'),
  bundle_price_label: localizeUk('від 950 грн/міс (seed)'),
  trial_lesson_text: localizeUk('Перше заняття — демо безкоштовно'),
  subjects_section_title: localizeUk('Предмети (колекція)'),
  subjects_discount_intro: localizeUk('Знижка 15% на 2+ предмети (seed)'),
  card_default_duration: localizeUk('4 міс.'),
  card_default_group_size: localizeUk('до 10 осіб'),
  advantages: [
    { title: localizeUk('Ментор 1:1'), description: localizeUk('Компонент advantages'), icon_key: 'users', order: 1 },
    { title: localizeUk('Щотижневі моки'), description: localizeUk('Пробні тести в seed-розкладі'), icon_key: 'clipboard', order: 2 },
    { title: localizeUk('Гнучкий формат'), description: localizeUk('Онлайн / офлайн'), icon_key: 'monitor', order: 3 },
  ],
  schedule_section_title: localizeUk('Розклад (seed)'),
  schedule_section_subtitle: localizeUk('Компонент schedule_rows'),
  schedule_rows: [
    { day: localizeUk('Пн'), time: '16:00 – 17:30', subject: localizeUk('Математика'), format: localizeUk('Офлайн'), order: 1 },
    { day: localizeUk('Ср'), time: '16:00 – 17:30', subject: localizeUk('Історія'), format: localizeUk('Онлайн'), order: 2 },
    { day: localizeUk('Пт'), time: '10:00 – 12:00', subject: localizeUk('Мок-НМТ'), format: localizeUk('Офлайн'), order: 3 },
  ],
  schedule_footnote: localizeUk('Розклад seed v2 — уточнюйте в Strapi admin.'),
  org_section_title: localizeUk('Організація навчання (seed)'),
  org_items: [
    { title: localizeUk('Тривалість'), description: localizeUk('4–6 місяців'), icon_key: 'clock', order: 1 },
    { title: localizeUk('Групи'), description: localizeUk('До 10 учнів'), icon_key: 'users', order: 2 },
    { title: localizeUk('Платформа'), description: localizeUk('LMS-демо'), icon_key: 'monitor', order: 3 },
  ],
  steps: [
    { n: 1, title: localizeUk('Заявка'), description: localizeUk('Форма на /apply'), order: 1 },
    { n: 2, title: localizeUk('Діагностика'), description: localizeUk('Визначаємо рівень'), order: 2 },
    { n: 3, title: localizeUk('НМТ'), description: localizeUk('Готуємо до іспиту'), order: 3 },
  ],
});

export const getPreUniversityPageEn = () => ({
  hero_title: localizeEn('NMT block seed v2'),
  hero_subtitle: localizeEn('pre-university-page + pre-university-group collection for subject cards.'),
  hero_badge: localizeEn('Demo intake · CMS check'),
  nmt_exam_date: '2026-06-12',
  countdown_label: localizeEn('until demo NMT date'),
  bundle_title: localizeEn('Bundle: Math + History'),
  bundle_description: localizeEn('Bundle copy from single type — not frontend code.'),
  bundle_price_label: localizeEn('from 950 UAH/mo (seed)'),
  trial_lesson_text: localizeEn('First lesson — demo free'),
  subjects_section_title: localizeEn('Subjects (collection)'),
  subjects_discount_intro: localizeEn('15% off 2+ subjects (seed)'),
  card_default_duration: localizeEn('4 mo.'),
  card_default_group_size: localizeEn('up to 10'),
  advantages: [
    { title: localizeEn('1:1 mentor'), description: localizeEn('advantages component'), icon_key: 'users', order: 1 },
    { title: localizeEn('Weekly mocks'), description: localizeEn('Mock tests in seed schedule'), icon_key: 'clipboard', order: 2 },
    { title: localizeEn('Flexible format'), description: localizeEn('Online / offline'), icon_key: 'monitor', order: 3 },
  ],
  schedule_section_title: localizeEn('Schedule (seed)'),
  schedule_section_subtitle: localizeEn('schedule_rows component'),
  schedule_rows: [
    { day: localizeEn('Mon'), time: '16:00 – 17:30', subject: localizeEn('Mathematics'), format: localizeEn('Offline'), order: 1 },
    { day: localizeEn('Wed'), time: '16:00 – 17:30', subject: localizeEn('History'), format: localizeEn('Online'), order: 2 },
    { day: localizeEn('Fri'), time: '10:00 – 12:00', subject: localizeEn('Mock NMT'), format: localizeEn('Offline'), order: 3 },
  ],
  schedule_footnote: localizeEn('Seed v2 schedule — confirm in Strapi admin.'),
  org_section_title: localizeEn('How we teach (seed)'),
  org_items: [
    { title: localizeEn('Duration'), description: localizeEn('4–6 months'), icon_key: 'clock', order: 1 },
    { title: localizeEn('Groups'), description: localizeEn('Up to 10 students'), icon_key: 'users', order: 2 },
    { title: localizeEn('Platform'), description: localizeEn('LMS demo'), icon_key: 'monitor', order: 3 },
  ],
  steps: [
    { n: 1, title: localizeEn('Application'), description: localizeEn('Form at /apply'), order: 1 },
    { n: 2, title: localizeEn('Diagnostic'), description: localizeEn('We assess level'), order: 2 },
    { n: 3, title: localizeEn('NMT'), description: localizeEn('Exam prep'), order: 3 },
  ],
});
